### ISSUE TITLE
when I complie with c++ ，is error

### ISSUE THREAD

**Issue by h-acker** [runner365/cpp_media_server#1]
cpp_media_server/net/webrtc/support_rtc_info.cpp:68:1: sorry, unimplemented: non-trivial designated initializers not supported
};
 ^
cpp_media_server/net/webrtc/support_rtc_info.cpp:68:1: sorry, unimplemented: non-trivial designated initializers not supported
cpp_media_server/net/webrtc/support_rtc_info.cpp:68:1: sorry, unimplemented: non-trivial designated initializers not supported
cpp_media_server/net/webrtc/support_rtc_info.cpp:68:1: sorry, unimplemented: non-trivial designated initializers not supported
[ 70%] Building CXX object CMakeFiles/cpp_media_server.dir/net/httpflv/httpflv_server.cpp.o
[ 71%] Building CXX object CMakeFiles/cpp_media_server.dir/net/httpflv/httpflv_writer.cpp.o

**Comment by h-acker** [comment]
change  gcc 9.4 , everything is ok

**Comment by runner365** [comment]
是的，推荐gcc8.4版本以上来编译。
