### ISSUE TITLE
1.0代码编译不过

### ISSUE THREAD

**Issue by mtdxc** [runner365/cpp_media_server#3]
好像是缺少src/net/hls目录，将外面的hls目录拷贝进去也不能编译

**Comment by runner365** [comment]
确实有这个问题，我晚上回家修复一下，合入代码的时候，不小心.gitignore中加入了hls这个目录。
今天晚上回去修复一下。

**Comment by runner365** [comment]
> 好像是缺少src/net/hls目录，将外面的hls目录拷贝进去也不能编译

嗨，我中午休息时间，重新push上去了，感谢发现问题。

**Comment by mtdxc** [comment]
嗯，下午拉了下代码已经可以编译了，
外面那个net和format文件夹是不是没用了， 应该不久就会删除的吧。。

**Comment by runner365** [comment]
> 

是的，后面删除掉，我的错误，多多见谅
