### ISSUE TITLE
webrtc-client-sdk 推流错误（media_server Segmentation fault，导致 client websocket close）

### ISSUE THREAD

**Issue by Kevinnan-teen** [runner365/cpp_media_server#4]
### chrome浏览器输入 http://localhost/9091 ，进入 demo 界面后点击 join 选择要共享的屏幕。websocket 连接打开。
![](https://cdn.jsdelivr.net/gh/Kevinnan-teen/CDN/image-20220328031220474.png)
### chrome 开发者工具 console 输出如下结果。
![image](https://user-images.githubusercontent.com/60206767/160297138-7bc2347b-b7c3-402e-a04e-9063190efc02.png)
![](https://cdn.jsdelivr.net/gh/Kevinnan-teen/CDN/image-20220328031623235.png)
### cpp_media_server 日志没有输出错误信息[E]。
![image](https://user-images.githubusercontent.com/60206767/160297247-a83830e0-de5f-45ef-b389-6047c24eb477.png)

**Comment by runner365** [comment]
你好，你是修改了sdk，视频源是共享屏幕吗？
我只测试过摄像头，还没有测试过共享屏幕，js代码是修改成视频源是共享屏幕，对吧？
return await this._cameraStream.Open('camera');
这个地方是修改成了'screen’吗？
@Kevinnan-teen

**Comment by Kevinnan-teen** [comment]
是的，我把 Client.js 中的 camera 改为 screen了，视频源是共享屏幕。
另外，我在测试 camera 时遇到几个问题
（1）cpp_media_server 参数设置为 webrtc2rtmp 时，测试结果正确，使用 ffplay 可以播放浏览器推流的视频；
（2）cpp_media_server 参数设置为 rtmp2webrtc 时，使用 FFmpeg 推流，本地 server.log 输出如下：
`[I][2022-02-28 15:49:17.106][room_service.cpp:387]request keyframe publisherid:10000_video, subscriberid:fe983a2c894b4012be2438a9f300c3c9, media ssrc:10001
[I][2022-02-28 15:49:17.305][webrtc_session.cpp:609]receive keyframe request: rtcp ps feedback length:12, sender ssrc:1, media ssrc:10001
[I][2022-02-28 15:49:17.305][room_service.cpp:387]request keyframe publisherid:10000_video, subscriberid:fe983a2c894b4012be2438a9f300c3c9, media ssrc:10001
[E][2022-02-28 15:49:17.389][ws_session.cpp:217]websocket read error:Connection reset by peer
[I][2022-02-28 15:49:17.389][ws_server.cpp:71]remove websocket session id:192.168.3.148:52570
[I][2022-02-28 15:49:17.389][protoo_server.cpp:318]protoo server on close, error code:125, roomId:2001, uid:20000
`
但是在推流 10s 左右，浏览器页面崩溃（如下图所示）
![image](https://user-images.githubusercontent.com/60206767/160353062-409ac582-0a88-4a59-a7dd-8978d1f4fc90.png)
由于 client 端崩溃，导致 websocket 连接断开。
（3）cpp_media_server 参数设置为 webrtc 时，应该如何拉取 webrtc 的推流数据？

**Comment by runner365** [comment]
我把 Client.js 中的 camera 改为 screen了，视频源是共享屏幕。

这个问题我已经解决了，稍后更新代码。

（2）cpp_media_server 参数设置为 rtmp2webrtc 时，使用 FFmpeg 推流

这个问题，能贴一下ffmpeg的推流命令行吗？麻烦也检查一下h264是baseline profile，音频是opus吗？
@Kevinnan-teen

**Comment by Kevinnan-teen** [comment]
#### 1、cpp_media_server 参数设置为 rtmp2webrtc 时
FFmpeg 推流命令行：
`
ffmpeg -f x11grab -framerate 25 -video_size 1920x1080 -i $DISPLAY -f pulse -i alsa_output.usb-USB_Microphone_Maono_Fairy_2020_11_21-00.iec958-stereo.monitor -ac 2 -vcodec libx264 -preset ultrafast -b:v 2000k -acodec aac -f flv rtmp://192.168.3.148/2001/10000
`
刚才使用 obs 推流进行测试，浏览器页面没有崩溃，可以播放 webrtc 画面。但是画面有明显卡顿，大概 8 秒才刷新一次。
obs rtmp 串流输出设置：
![image](https://user-images.githubusercontent.com/60206767/160384861-f0f1bd44-6b25-4883-a4c1-37ffc497c954.png)

#### 2、cpp_media_server 参数设置为 webrtc 时
浏览器页面点击 join，显示 camera 画面。然后点击 publish，server.log 输出：
`
[I][2022-02-28 18:57:16.121][srtp_session.cpp:154]srtp session construct, type:<srtp write>, suite:CRYPTO_SUITE_AEAD_AES_256_GCM
[I][2022-02-28 18:57:16.121][srtp_session.cpp:154]srtp session construct, type:<srtp read>, suite:CRYPTO_SUITE_AEAD_AES_256_GCM
[E][2022-02-28 18:57:16.170][webrtc_session.cpp:406]rtp packet parse error:rtp payload length(224), pad length(224) error
[I][2022-02-28 18:57:16.170][rtp_recv_stream.cpp:22]rtp stream construct media type:video, ssrc:417298354, payload type:125, is rtx:0, clock rate:90000
[E][2022-02-28 18:57:16.186][webrtc_session.cpp:406]rtp packet parse error:rtp payload length(224), pad length(224) error
`

**Comment by runner365** [comment]
嗯，这里有几个问题：
1， x264的profile，需要配置：baseline
2，Tune需要zerolatency；
3，关键帧麻烦配置2秒一个
4，音频暂时不支持aac推流；

@Kevinnan-teen

**Comment by runner365** [comment]
如果你编译了我定制化的ffmpeg，可以用下面的命令行(有opus编码)：
ffmpeg -re -i source.flv -c:v libx264 -s 640x360 -profile:v baseline -r 15 -x264-params 'keyint=30:vbv-maxrate=1000:vbv-bufsize=2000' -c:a libopus -ar 48000 -ac 2 -ab 32k -f flv rtmp://127.0.0.1/2001/30001

如果没有编译我定制化的ffmpeg，可以用下面的命令行(无音频，webrtc没有声音，直播rtmp是可以听见声音的)：
ffmpeg -re -i hd2000tp.flv -c:v libx264 -s 640x360 -profile:v baseline -r 15 -x264-params 'keyint=30:vbv-maxrate=1000:vbv-bufsize=2000' -c:a aac -ar 44100 -ac 2 -ab 32k -f flv rtmp://127.0.0.1/2001/30001

@Kevinnan-teen
