### ISSUE TITLE
支持 HTML5 flv 播放

### ISSUE THREAD

**Issue by Kevinnan-teen** [runner365/cpp_media_server#6]
如果使用独立的流媒体服务器获取FLV流，必须在流媒体服务器上正确配置 Access-Control-Allow-Origin 头，以便跨源获取资源。
因此，在`src/net/http/http_common.hpp` 的 67 行 ：
`ss << proto_ << "/" << version_ << " " << status_code_ << " " << status_ << "\r\n";`
后添加 `ss << "Access-Control-Allow-Origin: *\r\n";`，允许所有资源都可以访问此流媒体服务器资源。
重新编译项目，执行`./objs/cpp_media_server -c ./conf/rtmp_httpflv.cfg` 测试 HTTP-FLV。
[bilibili flv.js 在线测试](http://bilibili.github.io/flv.js/demo/)

**Comment by runner365** [comment]
> 如果使用独立的流媒体服务器获取FLV流，必须在流媒体服务器上正确配置 Access-Control-Allow-Origin 头，以便跨源获取资源。 因此，在`src/net/http/http_common.hpp` 的 67 行 ： `ss << proto_ << "/" << version_ << " " << status_code_ << " " << status_ << "\r\n";` 后添加 `ss << "Access-Control-Allow-Origin: *\r\n";`，允许所有资源都可以访问此流媒体服务器资源。 重新编译项目，执行`./objs/cpp_media_server -c ./conf/rtmp_httpflv.cfg` 测试 HTTP-FLV。 [bilibili flv.js 在线测试](http://bilibili.github.io/flv.js/demo/)

问题已经解决，合入v1.0分支。欢迎试用。
